import { Metadata } from "next";
import { notFound } from "next/navigation";
import VpnDlyaClient from "./client";

const VPN_PAGES: Record<string, {
  title: string; metaTitle: string; metaDescription: string; h1: string;
  problem: string; solution: string; disclaimer?: string; color: string; features: string[];
}> = {
  instagram: {
    color: "#E1306C", title: "Instagram*",
    metaTitle: "VPN для Instagram* в России 2026 — разблокировать Instagram бесплатно",
    metaDescription: "Instagram* заблокирован в России. TUMAN VPN разблокирует Instagram за 10 секунд. 3 дня бесплатно, без карты.",
    h1: "VPN для Instagram* в России",
    disclaimer: "Instagram* — продукт компании Meta Platforms Inc.*, деятельность которой запрещена на территории РФ.",
    problem: "Instagram* заблокирован в России с марта 2022 года по решению Роскомнадзора. Без VPN открыть невозможно — лента, сторис, директ недоступны.",
    solution: "TUMAN VPN разблокирует Instagram* за 10 секунд. Лента, сторис, рилсы, директ — всё работает. Банки не ломаются благодаря Split Tunneling.",
    features: ["Лента и сторис без ограничений", "Директ и звонки работают", "Рилсы без задержек", "Банки не ломаются"],
  },
  facebook: {
    color: "#1877F2", title: "Facebook*",
    metaTitle: "VPN для Facebook* в России 2026 — разблокировать Facebook",
    metaDescription: "Facebook* заблокирован в России. TUMAN VPN открывает Facebook за 10 секунд. 3 дня бесплатно.",
    h1: "VPN для Facebook* в России",
    disclaimer: "Facebook* — продукт компании Meta Platforms Inc.*, деятельность которой запрещена на территории РФ.",
    problem: "Facebook* заблокирован в России с марта 2022 года. Лента, группы, бизнес-страницы и Messenger недоступны без VPN.",
    solution: "TUMAN VPN открывает Facebook* через европейские серверы. Лента, группы, Messenger, звонки — работают в полном объёме.",
    features: ["Лента новостей", "Группы и сообщества", "Messenger и звонки", "Бизнес-страницы"],
  },
  whatsapp: {
    color: "#25D366", title: "WhatsApp",
    metaTitle: "VPN для WhatsApp в России 2026 — если WhatsApp не работает",
    metaDescription: "WhatsApp не работает на LTE? TUMAN VPN восстанавливает WhatsApp. Звонки, видео, сообщения — без обрывов.",
    h1: "VPN для WhatsApp в России",
    problem: "Звонки в WhatsApp периодически не работают у ряда операторов. На LTE с белыми списками WhatsApp может не подключаться совсем.",
    solution: "TUMAN VPN обходит технические блокировки WhatsApp. Звонки, видеозвонки, голосовые — работают стабильно.",
    features: ["Звонки и видеозвонки", "Голосовые сообщения", "Работает на LTE", "Группы и каналы"],
  },
  youtube: {
    color: "#FF0000", title: "YouTube",
    metaTitle: "VPN для YouTube без тормозов 2026 — ускорить YouTube в России",
    metaDescription: "YouTube тормозит из-за ТСПУ. TUMAN VPN убирает замедление. 4K без буферизации. 3 дня бесплатно.",
    h1: "VPN для YouTube без тормозов",
    problem: "YouTube в России замедляется через ТСПУ. Видео грузится минутами, качество падает до 360p, Shorts зависают.",
    solution: "TUMAN VPN обходит ТСПУ. Видео в 4K без буферизации, Shorts мгновенно, стримы без лагов.",
    features: ["4K без буферизации", "Shorts без задержек", "Стримы без лагов", "Банки продолжают работать"],
  },
  discord: {
    color: "#5865F2", title: "Discord",
    metaTitle: "VPN для Discord в России 2026 — разблокировать Discord",
    metaDescription: "Discord лагает или заблокирован? TUMAN VPN стабилизирует Discord. Войс-чаты, стримы без лагов.",
    h1: "VPN для Discord в России",
    problem: "Discord периодически замедляется и блокируется. Войс-чаты лагают, стримы обрываются, серверы недоступны.",
    solution: "TUMAN VPN стабилизирует Discord. Войс-чаты, видеозвонки, стримы — работают без лагов.",
    features: ["Войс-чаты без лагов", "Стримы и Go Live", "Все серверы доступны", "Нитро работает"],
  },
  chatgpt: {
    color: "#10a37f", title: "ChatGPT",
    metaTitle: "VPN для ChatGPT в России 2026 — открыть ChatGPT, Claude, Midjourney",
    metaDescription: "ChatGPT недоступен в России. TUMAN VPN открывает ChatGPT, Claude, Midjourney. Европейский IP за 10 секунд.",
    h1: "VPN для ChatGPT в России",
    problem: "ChatGPT недоступен — OpenAI закрыл доступ для российских IP. Claude, Midjourney и другие AI-сервисы тоже.",
    solution: "TUMAN VPN даёт европейский IP — ChatGPT, Claude, Midjourney работают. GPT-4, генерация, API — всё доступно.",
    features: ["ChatGPT и GPT-4", "Claude от Anthropic", "Midjourney и DALL-E", "Все AI-сервисы"],
  },
  tiktok: {
    color: "#000000", title: "TikTok",
    metaTitle: "VPN для TikTok в России 2026 — полный TikTok без ограничений",
    metaDescription: "TikTok ограничил функции для России. TUMAN VPN открывает полный TikTok. 3 дня бесплатно.",
    h1: "VPN для TikTok в России",
    problem: "TikTok ограничил ряд функций для российских пользователей. Часть контента недоступна, монетизация отключена.",
    solution: "TUMAN VPN открывает полный TikTok. Весь контент, загрузка видео, прямые эфиры — без ограничений.",
    features: ["Весь контент", "Загрузка видео", "Прямые эфиры", "Монетизация"],
  },
  spotify: {
    color: "#1DB954", title: "Spotify",
    metaTitle: "VPN для Spotify в России 2026 — вернуть Spotify",
    metaDescription: "Spotify ушёл из России. TUMAN VPN возвращает Spotify. Музыка, подкасты. 3 дня бесплатно.",
    h1: "VPN для Spotify в России",
    problem: "Spotify ушёл из России в 2022. Приложение не открывается, стриминг недоступен.",
    solution: "TUMAN VPN возвращает Spotify через финский сервер. Музыка, подкасты, офлайн — всё работает.",
    features: ["Вся музыка и подкасты", "Офлайн-треки", "Семейная подписка", "Оплата через VPN"],
  },
  netflix: {
    color: "#E50914", title: "Netflix",
    metaTitle: "VPN для Netflix в России 2026 — открыть Netflix",
    metaDescription: "Netflix недоступен в России. TUMAN VPN открывает Netflix. Европейская библиотека. 3 дня бесплатно.",
    h1: "VPN для Netflix в России",
    problem: "Netflix приостановил работу в России. Карты не принимаются, контент заблокирован.",
    solution: "TUMAN VPN открывает Netflix. Финская и немецкая библиотека — Full HD и 4K.",
    features: ["Тысячи фильмов", "Оригинальный контент", "Full HD и 4K", "Оплата через VPN"],
  },
  telegram: {
    color: "#2AABEE", title: "Telegram",
    metaTitle: "VPN для Telegram в России 2026 — если Telegram не работает на LTE",
    metaDescription: "Telegram не работает на LTE? TUMAN VPN оптимизирован для LTE-блокировок. 3 дня бесплатно.",
    h1: "VPN для Telegram на LTE в России",
    problem: "На LTE с белыми списками Telegram может не открываться. Оператор разрешает только отечественные сайты.",
    solution: "TUMAN VPN оптимизирован для LTE-блокировок. Маскировка под VK — работает в самых жёстких условиях.",
    features: ["Работает на LTE", "Маскировка под VK", "Звонки и видео", "Каналы и боты"],
  },
  threads: {
    color: "#000000", title: "Threads*",
    metaTitle: "VPN для Threads* в России 2026 — открыть Threads",
    metaDescription: "Threads* заблокирован в России. TUMAN VPN открывает Threads. 3 дня бесплатно.",
    h1: "VPN для Threads* в России",
    disclaimer: "Threads* — продукт компании Meta Platforms Inc.*, деятельность которой запрещена на территории РФ.",
    problem: "Threads* заблокирован как часть экосистемы Meta*. Приложение не открывается.",
    solution: "TUMAN VPN открывает Threads*. Лента, уведомления, ответы — без ограничений.",
    features: ["Лента без ограничений", "Уведомления работают", "Связь с Instagram*", "Публикации и ответы"],
  },
  twitter: {
    color: "#000000", title: "Twitter/X",
    metaTitle: "VPN для Twitter/X в России 2026 — разблокировать Twitter",
    metaDescription: "Twitter/X замедлён в России. TUMAN VPN разблокирует Twitter без лагов. 3 дня бесплатно.",
    h1: "VPN для Twitter/X в России",
    problem: "Twitter (X) замедлён и периодически блокируется в России. Лента грузится долго, медиа не открывается.",
    solution: "TUMAN VPN убирает замедление Twitter/X. Лента, Spaces, видео — работают мгновенно.",
    features: ["Лента без замедления", "Spaces и аудио", "Видео без буферизации", "Все медиа доступны"],
  },
  pinterest: {
    color: "#E60023", title: "Pinterest",
    metaTitle: "VPN для Pinterest в России 2026 — открыть Pinterest",
    metaDescription: "Pinterest недоступен? TUMAN VPN открывает Pinterest в России. 3 дня бесплатно.",
    h1: "VPN для Pinterest в России",
    problem: "Pinterest периодически блокируется или замедляется в России. Пины не грузятся, поиск не работает.",
    solution: "TUMAN VPN открывает Pinterest через европейские серверы. Пины, доски, поиск — всё работает.",
    features: ["Все пины доступны", "Поиск работает", "Сохранение на доски", "HD изображения"],
  },
  linkedin: {
    color: "#0A66C2", title: "LinkedIn",
    metaTitle: "VPN для LinkedIn в России 2026 — разблокировать LinkedIn",
    metaDescription: "LinkedIn заблокирован в России с 2016. TUMAN VPN открывает LinkedIn за 10 секунд. 3 дня бесплатно.",
    h1: "VPN для LinkedIn в России",
    problem: "LinkedIn заблокирован в России с ноября 2016 года по решению Роскомнадзора. Профили, вакансии, сообщения недоступны.",
    solution: "TUMAN VPN разблокирует LinkedIn. Профиль, вакансии, InMail, Premium — всё работает.",
    features: ["Профиль и контакты", "Поиск вакансий", "InMail сообщения", "LinkedIn Learning"],
  },
  twitch: {
    color: "#9146FF", title: "Twitch",
    metaTitle: "VPN для Twitch в России 2026 — смотреть Twitch без лагов",
    metaDescription: "Twitch лагает в России? TUMAN VPN ускоряет Twitch. Стримы без буферизации. 3 дня бесплатно.",
    h1: "VPN для Twitch в России",
    problem: "Twitch замедляется через ТСПУ. Стримы буферизируются, качество падает, чат лагает.",
    solution: "TUMAN VPN обходит замедление. Стримы в 1080p без буферизации, чат работает мгновенно.",
    features: ["Стримы без лагов", "1080p качество", "Чат без задержек", "Подписки и биты"],
  },
  reddit: {
    color: "#FF4500", title: "Reddit",
    metaTitle: "VPN для Reddit в России 2026 — открыть Reddit",
    metaDescription: "Reddit заблокирован в России. TUMAN VPN открывает Reddit. 3 дня бесплатно.",
    h1: "VPN для Reddit в России",
    problem: "Reddit заблокирован Роскомнадзором. Сабреддиты, комментарии, медиа — всё недоступно без VPN.",
    solution: "TUMAN VPN открывает Reddit полностью. Все сабреддиты, комментарии, медиа — работают.",
    features: ["Все сабреддиты", "Комментарии и посты", "Медиа и видео", "Reddit Premium"],
  },
  snapchat: {
    color: "#FFFC00", title: "Snapchat",
    metaTitle: "VPN для Snapchat в России 2026 — если Snapchat не работает",
    metaDescription: "Snapchat не работает в России? TUMAN VPN восстанавливает Snapchat. 3 дня бесплатно.",
    h1: "VPN для Snapchat в России",
    problem: "Snapchat периодически не работает у российских операторов. Снэпы не отправляются, линзы не грузятся.",
    solution: "TUMAN VPN стабилизирует Snapchat. Снэпы, сторис, линзы, Spotlight — всё работает.",
    features: ["Снэпы и сторис", "AR-линзы", "Видеозвонки", "Spotlight"],
  },
  zoom: {
    color: "#2D8CFF", title: "Zoom",
    metaTitle: "VPN для Zoom в России 2026 — стабильный Zoom",
    metaDescription: "Zoom нестабильно работает? TUMAN VPN улучшает качество Zoom. Без обрывов. 3 дня бесплатно.",
    h1: "VPN для Zoom в России",
    problem: "Zoom ограничил функции для России. Качество звонков нестабильно, подключение обрывается.",
    solution: "TUMAN VPN стабилизирует Zoom. HD-видео, демонстрация экрана, групповые звонки — без обрывов.",
    features: ["HD видеозвонки", "Демонстрация экрана", "Групповые конференции", "Без обрывов"],
  },
  skype: {
    color: "#00AFF0", title: "Skype",
    metaTitle: "VPN для Skype в России 2026 — стабильный Skype",
    metaDescription: "Skype не работает стабильно? TUMAN VPN улучшает качество Skype. 3 дня бесплатно.",
    h1: "VPN для Skype в России",
    problem: "Skype периодически работает нестабильно в России. Звонки обрываются, качество падает.",
    solution: "TUMAN VPN стабилизирует Skype через европейские серверы. Звонки, видео, чат — работают стабильно.",
    features: ["Звонки без обрывов", "Видео HD качество", "Чат и файлы", "Skype для бизнеса"],
  },
  viber: {
    color: "#7360F2", title: "Viber",
    metaTitle: "VPN для Viber в России 2026 — если Viber не работает на LTE",
    metaDescription: "Viber не работает на LTE? TUMAN VPN восстанавливает Viber. Звонки и сообщения. 3 дня бесплатно.",
    h1: "VPN для Viber в России",
    problem: "Viber периодически блокируется на LTE у некоторых операторов. Звонки не проходят, сообщения не доставляются.",
    solution: "TUMAN VPN обходит блокировки Viber. Звонки, видеозвонки, сообщения — работают на любом операторе.",
    features: ["Звонки и видео", "Сообщения без задержек", "Работает на LTE", "Viber Out звонки"],
  },
  signal: {
    color: "#3A76F0", title: "Signal",
    metaTitle: "VPN для Signal в России 2026 — открыть Signal",
    metaDescription: "Signal заблокирован в России. TUMAN VPN открывает Signal. Безопасная переписка. 3 дня бесплатно.",
    h1: "VPN для Signal в России",
    problem: "Signal заблокирован Роскомнадзором. Сообщения не доставляются, звонки не проходят.",
    solution: "TUMAN VPN разблокирует Signal. Шифрованные сообщения, звонки, группы — всё работает.",
    features: ["Шифрованные сообщения", "Звонки и видео", "Группы и каналы", "Исчезающие сообщения"],
  },
  onlyfans: {
    color: "#00AFF0", title: "OnlyFans",
    metaTitle: "VPN для OnlyFans в России 2026 — открыть OnlyFans",
    metaDescription: "OnlyFans ограничен в России. TUMAN VPN открывает OnlyFans. 3 дня бесплатно.",
    h1: "VPN для OnlyFans в России",
    problem: "OnlyFans ограничивает доступ для российских IP. Оплата российскими картами невозможна.",
    solution: "TUMAN VPN даёт европейский IP. OnlyFans открывается полностью, контент доступен.",
    features: ["Полный доступ", "Все авторы", "Подписки работают", "Европейский IP"],
  },
  pornhub: {
    color: "#FF9000", title: "Pornhub",
    metaTitle: "VPN для Pornhub в России 2026 — разблокировать Pornhub",
    metaDescription: "Pornhub заблокирован в России. TUMAN VPN разблокирует Pornhub. 3 дня бесплатно.",
    h1: "VPN для Pornhub в России",
    problem: "Pornhub и другие сайты для взрослых заблокированы Роскомнадзором.",
    solution: "TUMAN VPN обходит блокировку через европейские серверы. Полный доступ без ограничений.",
    features: ["Полный доступ", "HD качество", "Без ограничений", "Анонимность"],
  },
  steam: {
    color: "#1B2838", title: "Steam",
    metaTitle: "VPN для Steam в России 2026 — полный Steam без ограничений",
    metaDescription: "Steam ограничил оплату и контент для России. TUMAN VPN открывает полный Steam. 3 дня бесплатно.",
    h1: "VPN для Steam в России",
    problem: "Steam ограничил оплату для российских карт. Часть игр недоступна в российском регионе, цены завышены.",
    solution: "TUMAN VPN даёт доступ к полному каталогу Steam. Европейский IP для покупок и загрузки.",
    features: ["Полный каталог игр", "Европейские цены", "Workshop и Community", "Быстрая загрузка"],
  },
  gaming: {
    color: "#00FF87", title: "VPN для игр",
    metaTitle: "VPN для онлайн-игр 2026 — без лагов и пинга",
    metaDescription: "Высокий пинг в играх? TUMAN VPN снижает пинг до европейских серверов. 3 дня бесплатно.",
    h1: "VPN для онлайн-игр без лагов",
    problem: "Высокий пинг до европейских серверов. Игры лагают, матчи обрываются, регион заблокирован.",
    solution: "TUMAN VPN оптимизирует маршрут до игровых серверов. Низкий пинг, стабильное соединение.",
    features: ["Низкий пинг", "Стабильное соединение", "Все регионы", "Valorant, CS2, Dota 2"],
  },
  trading: {
    color: "#F0B90B", title: "VPN для трейдинга",
    metaTitle: "VPN для трейдинга в России 2026 — доступ к биржам",
    metaDescription: "Биржи заблокированы? TUMAN VPN открывает Binance, Bybit, OKX. 3 дня бесплатно.",
    h1: "VPN для трейдинга в России",
    problem: "Крупные криптобиржи ограничивают доступ для российских IP. Binance, Bybit, OKX — частичная блокировка.",
    solution: "TUMAN VPN даёт европейский IP. Все биржи работают, торговля без ограничений.",
    features: ["Binance и Bybit", "OKX и Kraken", "Быстрое соединение", "Стабильный IP"],
  },
  binance: {
    color: "#F0B90B", title: "Binance",
    metaTitle: "VPN для Binance в России 2026 — открыть Binance",
    metaDescription: "Binance ограничил Россию. TUMAN VPN открывает Binance полностью. 3 дня бесплатно.",
    h1: "VPN для Binance в России",
    problem: "Binance ограничил функции для российских пользователей. Часть торговых пар недоступна, P2P ограничен.",
    solution: "TUMAN VPN открывает Binance через финский IP. Все торговые пары, фьючерсы, P2P — работают.",
    features: ["Все торговые пары", "Фьючерсы и маржа", "P2P без ограничений", "Европейский IP"],
  },
  paypal: {
    color: "#003087", title: "PayPal",
    metaTitle: "VPN для PayPal в России 2026 — открыть PayPal",
    metaDescription: "PayPal ушёл из России. TUMAN VPN помогает открыть PayPal. 3 дня бесплатно.",
    h1: "VPN для PayPal в России",
    problem: "PayPal приостановил работу в России. Переводы, оплата, получение средств — недоступны.",
    solution: "TUMAN VPN даёт европейский IP для доступа к PayPal. Просмотр баланса и история доступны.",
    features: ["Доступ к аккаунту", "Просмотр баланса", "История операций", "Европейский IP"],
  },
  amazon: {
    color: "#FF9900", title: "Amazon",
    metaTitle: "VPN для Amazon в России 2026 — покупки на Amazon",
    metaDescription: "Amazon не доставляет в Россию? TUMAN VPN помогает с доступом. 3 дня бесплатно.",
    h1: "VPN для Amazon в России",
    problem: "Amazon ограничил доставку в Россию. Часть контента Prime Video недоступна, цены завышены.",
    solution: "TUMAN VPN открывает Amazon и Prime Video через европейский IP. Полный каталог доступен.",
    features: ["Amazon Shopping", "Prime Video", "Kindle книги", "Европейские цены"],
  },
  ebay: {
    color: "#E53238", title: "eBay",
    metaTitle: "VPN для eBay в России 2026 — покупки на eBay",
    metaDescription: "eBay ограничил Россию? TUMAN VPN помогает с доступом к eBay. 3 дня бесплатно.",
    h1: "VPN для eBay в России",
    problem: "eBay ограничил часть функций для российских пользователей. Оплата и доставка затруднены.",
    solution: "TUMAN VPN даёт европейский IP для полного доступа к eBay. Все лоты и продавцы доступны.",
    features: ["Все лоты доступны", "Аукционы работают", "Европейские продавцы", "PayPal оплата"],
  },
};

type Props = { params: { app: string } };

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const page = VPN_PAGES[params.app];
  if (!page) return { title: "TUMAN VPN" };
  return {
    title: page.metaTitle,
    description: page.metaDescription,
    openGraph: { title: page.metaTitle, description: page.metaDescription, siteName: "TUMAN VPN", type: "website" },
    alternates: { canonical: `https://tuman.help/vpn-dlya/${params.app}` },
  };
}

export async function generateStaticParams() {
  return Object.keys(VPN_PAGES).map((app) => ({ app }));
}

export default function VpnDlyaPage({ params }: Props) {
  const page = VPN_PAGES[params.app];
  if (!page) notFound();
  const otherApps = Object.entries(VPN_PAGES).filter(([k]) => k !== params.app).map(([k, v]) => ({ slug: k, title: v.title }));
  return <VpnDlyaClient page={page} slug={params.app} otherApps={otherApps} />;
}
